{{ config(materialized='table') }}

select  CONTINENT, country, LOCATION_LEVEL, ISLAND, LOCATION, AREA_KM_2_ as area,LATITUDE, LONGITUDE, time_zone from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_MONNIL_ROY" 
group by CONTINENT, country, LOCATION_LEVEL, ISLAND, LOCATION, AREA_KM_2_,LATITUDE, LONGITUDE, time_zone